### ISSUE TITLE
Truncated value when size close to or greater than 4KB

### ISSUE THREAD

**Issue by mdorier** [symisc/unqlite#136]
I have an application that uses the key/value store interface of an unqlite database (more specifically `unqlite_kv_store` and `unqlite_kv_fetch_callback`). When I store values close to or above 4KB (I haven't looked at the exact threshold) the value gets truncated and I only get back the last few bytes.

For instance, with a key of 20 bytes and a value of 4069 bytes, fetching back the value for that key only returns the last 11 bytes of the value. With a value of 4064 

This only happens with a file-based database. If I use an in-memory database, the same code works perfectly fine.

Note: the database file is stored on an NVMe, if that matters. I also tried storing the file in `/dev/shm` and I get the same problem.

**Comment by symisc** [comment]
If the stored payload if larger than a single UnQLite page size  which **defaults to 4KB**, then `unqlite_kv_fetch_callback()` **calls your supplied callback multiple times (and not a single call)**. Probably you are erasing the previous data returned `by unqlite_kv_fetch_callback()`, via simple assignment that's why you got the last 11 bytes from your payload.
