### ISSUE TITLE
Can unqlite do mirroring?

### ISSUE THREAD

**Issue by nokemono** [symisc/unqlite#145]
Can unqlite do mirroring?
I would like to mirror unqlite stored on another PC if possible.

**Comment by symisc** [comment]
UnQLite follows the SQLite paradigm by using a single file as datastore. Backups & Mirroring are easy handled by external software since it involves moving a single file only.

Symisc Systems, SUARL

-----Original Message-----
From: nokemono ***@***.***>
To: symisc/unqlite ***@***.***>
Cc: Subscribed ***@***.***>
Sent: Mon, 28 Nov 2022 18:39
Subject: [symisc/unqlite] Can unqlite do mirroring? (Issue #145)

Can unqlite do mirroring?
I would like to mirror unqlite stored on another PC if possible.

-- 
Reply to this email directly or view it on GitHub:
https://github.com/symisc/unqlite/issues/145
