### ISSUE TITLE
Maximum Key Size?

### ISSUE THREAD

**Issue by VaslD** [symisc/unqlite#152]
**Is there a max key size for UnQLite? Or on Apple platforms?**

-----

I was writing a Swift wrapper for UnQLite on iOS, and I did a simple unit test to make sure my wrapper was running correctly. The tests failed. So I rewrote the tests to call C-functions instead, and it still failed. 🤣

Basically I was generating random-length keys and values, storing them in a database, closing it, and retrieving everything to compare with an in-memory Swift dictionary. The order wouldn't matter, but I would expect key and value comparisons return exactly the same.

Everything seemed OK until the key size went above `4000`. (Sorry I couldn't remember the exact tipping point.)

I was calling `unqlite_kv_fetch()` with a null pointer to retrieve data size pointed by `key` (first, then the buffer stuff, doesn't matter here). Then I had -6 thrown in Swift, translated to constant `UNQLITE_NOTFOUND`.

It was alarming because (A) no matter how many tests I ran (or whatever database engine file/memory I chose), with keys less than 4000 bytes the test always succeeded; and (B) the test also succeeded with 4000+ bytes key size if I changed the test to retrieve the value immediate after storing it (without committing and reopening the database).

I made me believe that UnQLite was not properly persisting key-value pairs with key size > 4000 bytes, unless Swift array/dictionary were buggy (very unlikely).

So if there wasn't a 4000-something max key size, can you run a unit test with keys sized within 4000 and 5000 range (say around 4096), close and reopen the database handle, then retrieve the same value with the same key? I'd help but I don't do C much. I'm afraid my C code would introduce more bugs than the ones I'm trying to figure out.

BTW, I *can* provide a working (or rather failing) unit test project if you don't mind seeing Swift code. It calls down to C anyway, with boilerplates.

**Comment by symisc** [comment]
Hello,

**There is no limit on the key size imposed by the UnQLite engine**, but  for maximum efficiency, prefer using _keys_ smaller than the used **page size** which is set to **4096 bytes by default**.

Finally, The recommended interface for extracting very large data from the database is [unqlite_kv_fetch_callback()](https://unqlite.org/c_api/unqlite_kv_fetch_callback.html) where the user simply need to supply a consumer callback instead of a buffer which may be unacceptable when dealing with very large records.
