### ISSUE TITLE
unqlite_open behaviour on UNQLITE_OPEN_READWRITE and UNQLITE_OPEN_READONLY modes

### ISSUE THREAD

**Issue by woldendans** [symisc/unqlite#25]
Hello,

In the [unqlite_open documentation page](http://unqlite.org/c_api/unqlite_open.html), it is specified that, if UNQLITE_OPEN_READWRITE is used:

> Open the database with read+write privileges. If the database does not exists, an error code is returned.

I would expect this behaviour to be true for UNQLITE_OPEN_READONLY too.

Yet, what I observe is that even if the DB does not exists, the return code is *UNQLITE_OK*. But if you call any funtion using the returned handle (like a store instruction), you will get a *UNQLITE_IOERR* return code.

What is the real expected behaviour? The one specified is appealing because it allow us to check immediatly if the DB exists instead of waiting for a first instruction to be made.

**Comment by symisc** [comment]
The reason for that is that unqlite_open() does not deal with disk operation at all. That is, it merely prepare the db handle, allocate the internal stuff and so forth. Disk operation starts with the first call to unqllte_kv_store(), unqlite_kv_fetch(), etc.

The function should be named unqlite_initi() instead of unqlite_open().
