### ISSUE TITLE
unqlite_open UNQLITE_OPEN_READWRITE invalid behavior

### ISSUE THREAD

**Issue by shibormot** [symisc/unqlite#40]
I found that library does not report error if open nonexistent database without OPEN_CREATE mode

```
#include <stdio.h>
#include "unqlite.h"

int main(int argc, char **argv) {
    char *filename = "nonexistent.db";
    unqlite *handle;
    int rc;

    printf("Unqlite version: %s\n", UNQLITE_VERSION);
    printf("Unqlite version number: %d\n", UNQLITE_VERSION_NUMBER);

    rc = unqlite_open(&handle, filename, UNQLITE_OPEN_READWRITE);
    if (rc == 0) {
        printf("Invalid behavior: Zero error on nonexistent db file\n");
        return 0;
    }
    printf("Valid behavior: Non-zero error on nonexistent db file\n");
    return 0;
}

```

I get following output:

> Unqlite version: 1.1.6
> Unqlite version number: 1001006
> Invalid behavior: Zero error on nonexistent db file

**Comment by topilski** [comment]
Same behavior Windows/Linux/MacOSX

**Comment by symisc** [comment]
If you read the documentation carefully, you must already know that **unqlite_open()** does not touch the disk at all regardless of the flag you set which is saved for later use. 
In other word, your flag is verified on the first call to one of the read or write functions _(unqlite_kv_store(), kv_read(), etc.)_ which in turn will return **UNQLITE_IO** since you set a read-only flag and the file must exist on disk.
   
In fact, unqlite_open() should be renamed **unqlite_init()** instead!
