### ISSUE TITLE
Question about thread-safety

### ISSUE THREAD

**Issue by coleifer** [symisc/unqlite#71]
On the homepage it says "thread-safe and full(y) reentrant", but if you look at the [compiler flags](https://unqlite.org/c_api_const.html), it seems to indicate that it is not thread-safe by default?

> *UNQLITE_ENABLE_THREADS*
>
> This option controls whether or not code is included in UnQLite to enable it to operate safely in a multithreaded environment. The default is not. All mutexing code is omitted and it is unsafe to use UnQLite in a multithreaded program. When compiled with the UNQLITE_ENABLE_THREADS directive enabled, UnQLite can be used in a multithreaded program and it is safe to share the same virtual machine and database handle between two or more threads.

Could you help me understand the difference?

**Comment by endlesstravel** [comment]
same question.
And I think it's thread-safe **only if UNQLITE_ENABLE_THREADS  is used in compiling.**

**Comment by endlesstravel** [comment]
## Reference 
https://crates.io/crates/unqlite-sys


## Threadsafe
Note that even "enable-threads" is featured in your crate, it's not meant that your code is threadsafe.

When UnQLite has been compiled with threading support then the threading mode can be altered at run-time using the unqlite_lib_config() interface together with one of these verbs:

UNQLITE_LIB_CONFIG_THREAD_LEVEL_SINGLE

UNQLITE_LIB_CONFIG_THREAD_LEVEL_MULTI

Platforms others than Windows and UNIX systems must install their own mutex subsystem via unqlite_lib_config() with a configuration verb set to UNQLITE_LIB_CONFIG_USER_MUTEX. Otherwise the library is not threadsafe.

Note that you must link UnQLite with the POSIX threads library under UNIX systems (i.e: -lpthread).

To use in multithread cases, that is threadsafe, you may use like this:

```rs
extern crate unqlite_sys as ffi;
use ffi::constants as ffic;

fn main() {
    unsafe {
        ffi::unqlite_lib_config(ffic::UNQLITE_LIB_CONFIG_THREAD_LEVEL_MULTI);
        ffi::unqlite_lib_init();
        assert_eq!(ffi::unqlite_lib_is_threadsafe(), 1);

        // do stuff ...

    }
}
```

**Comment by symisc** [comment]
Yes, Windows & UNIXEs have a pre-built mutex interface shipped with UnQLite so you don't have to ship your own mutex subsystem to synchronize concurrent threads. And yes, you have to **compile UnQLite with threading support**, and enable multi-threading at run-time **just exactly what you did**! Find out more information about threading support here at: https://unqlite.org/c_api_const.html#compile_time
